### ISSUE TITLE
Build error triggered from the mxpv/podsync makefile

### ISSUE THREAD

**Issue by elsiehupp** [hashicorp/go-multierror#38] opened 2020-06-20 01:20 UTC
I am trying to build `mxpv/podsync` using its makefile, and I am getting this error:
> \# github.com/hashicorp/go-multierror
> ../go/src/github.com/hashicorp/go-multierror/multierror.go:112:9: undefined: errors.As
> ../go/src/github.com/hashicorp/go-multierror/multierror.go:117:9: undefined: errors.Is

I know basically nothing about `go`, but as far as I can tell this shouldn't be happening. Is this a bug in the `podsync` makefile, or is it a bug in `multierror.go`?

I would appreciate the attention of someone who understands these things better than I. Thanks!

[(For further context, see my issue on the `podsync` repository here.)](https://github.com/mxpv/podsync/issues/100)

**Comment by jefferai** [comment] 2020-06-20 02:26
You need to be using Go 1.13 or higher as that's when the errors package was introduced.

**Comment by elsiehupp** [comment] 2020-06-21 13:23
> You need to be using Go 1.13 or higher as that's when the errors package was introduced.

Thanks for the explainer! Do you think it would be possible for someone to update the code so that it would produce a more useful error message when trying to build it with the wrong version of `go`?

**Comment by mwhooker** [comment] 2020-10-02 22:14
Hi @elsiehupp, sorry you had this problem. Unfortunately there's not much we can do to make the error message more apparent. However, later versions of go _do_ say when you're using a version of go that the module doesn't support. I think we should track this as a documentation request, and so am going to close it as a duplicate of #37 

I'll also copy some thoughts I shared over in that other ticket: my advice would be to use a version of go at most one "major" version out of date. To quote from the go release page:

> Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release.

**Closed by mwhooker** 2020-10-02 22:14 UTC
